# Generated by Django 4.1.2 on 2023-01-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_caption_post_like_count_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_caption',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
